services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: python resizinator/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/resizinator
  db:
    image: postgres:16
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
