# Generated by Django 5.0.6 on 2024-05-18 17:03

import django.db.models.deletion
import resizinator.storage_backends
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('image', '0001_initial'), ('image', '0002_alter_image_medium_alter_image_original_and_more')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.ImageField(storage=resizinator.storage_backends.PrivateMediaStorage, upload_to='')),
                ('small', models.ImageField(blank=True, null=True, storage=resizinator.storage_backends.PrivateMediaStorage, upload_to='')),
                ('medium', models.ImageField(blank=True, null=True, storage=resizinator.storage_backends.PrivateMediaStorage, upload_to='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
